### ISSUE TITLE
KeyError: 'people'

### ISSUE THREAD

**Issue by ubersec1** [mxrch/GHunt#502]
**Describe the bug**

When looking up an email, I get the following error.

**To Reproduce**
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\afuera\.local\bin\ghunt.exe\__main__.py", line 7, in <module>
  File "C:\Users\afuera\AppData\Local\pipx\pipx\venvs\ghunt\Lib\site-packages\ghunt\ghunt.py", line 18, in main
    parse_and_run()
  File "C:\Users\afuera\AppData\Local\pipx\pipx\venvs\ghunt\Lib\site-packages\ghunt\cli.py", line 31, in parse_and_run
    process_args(args)
  File "C:\Users\afuera\AppData\Local\pipx\pipx\venvs\ghunt\Lib\site-packages\ghunt\cli.py", line 41, in process_args
    asyncio.run(email.hunt(None, args.email_address, args.json))
  File "C:\Users\afuera\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\afuera\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\afuera\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\afuera\AppData\Local\pipx\pipx\venvs\ghunt\Lib\site-packages\ghunt\modules\email.py", line 24, in hunt
    is_found, target = await people_pa.people_lookup(as_client, email_address, params_template="just_name")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\afuera\AppData\Local\pipx\pipx\venvs\ghunt\Lib\site-packages\ghunt\apis\peoplepa.py", line 103, in people_lookup
    person_data = list(data["people"].values())[0]
                       ~~~~^^^^^^^^^^
KeyError: 'people'

**System (please complete the following information):**
 - OS - Win 11
 - Python version - 3.11.8

**Additional context**
I am aware of the other open/closed issues, but I run GHunt ver. 2.1.2. 
Hence, "GPLUS_ADDITIONAL_DATA" is already commented out. Switching the params_template from "max_details" to "just_name" did not change anything.

Thanks for your help.

**Comment by mxrch** [comment]
Hey, it's still working for me, on the version 2.1.2.
Can you try with larry@google.com ?

**Comment by mxrch** [comment]
If it doesn't work, can you try a `ghunt login --clean`, they doing the login again ?

**Comment by ubersec1** [comment]
Thanks for the quick reply! Using `ghunt login --clean` and a fresh account worked.

**Comment by cr4wler** [comment]
had this problem since last week as well.
`ghunt login --clean` and re-logging into the **same** account (via ghunt companion) as before did **not** work for me, still getting the error.
even for larry@google.com.

**Comment by ubersec1** [comment]
@cr4wler 
I guess it depends on the account used. I can replicate the issue with my "old" account - with the "new" account everything works fine.

**Comment by mxrch** [comment]
@cr4wler On what version are you trying ?

**Comment by cr4wler** [comment]
I'm on 2.1.2, pipx also says I'm on the newest version.
Running on Ubuntu 23.10 and newest python the default repos deliver.
I also believe it might have to do with the account. Nonetheless I think it should be checked WHY some accounts work and others don't.

**Comment by mxrch** [comment]
Yeah but no time for that unfortunately, it's an edge case that 0.00001% people has.

**Comment by cr4wler** [comment]
Just fyi, the REST api that is getting called returns a 403. This fits the "account is at fault" narrative.
Maybe add a check for the error and output an appropriate message that the account might have been "banned"?

`{'error': {'code': 403, 'message': 'The caller does not have permission', 'status': 'PERMISSION_DENIED'}}`

**Comment by StigP1337** [comment]
I have the same problem. I updated to 2.1.2 and logged in with a new account. GHunt worked for a couple of hours. Now I get the error again. New Login with the same account doesn't help. I logged in with another never used before account and I still get the error. The problem only occurs for E-Mail addresses for which a Google account exists. I used GHunt 2.1.0 for a couple of weeks without these problems before.

**Comment by mxrch** [comment]
Fixed, Google stopped the free access to their Vision API.

**Comment by mav-noob** [comment]
Hi,
I still get this error and I checked out the disabled Vision API version.

It seemed to me, that the error occurs in the PeoplePaHttp Class. The requested URL is https://people-pa.clients6.google.com/v2/people/lookup.
Did google also stop the free access for this API? Or maybe I don't get it? :)

Do I need to create a project over the google api console and grant access to the people api (like described here: https://developers.google.com/people/v1/getting-started?hl=en)?

Thanks

**Comment by E5GEN2** [comment]
I am getting this error
